allowBuilds:
    esbuild: true

onlyBuiltDependencies:
    - esbuild

overrides:
    esbuild@<=0.24.2: '>=0.25.0'
    picomatch@>=4.0.0 <4.0.4: '>=4.0.4'
    postcss@<=8.5.17: '>=8.5.18'
    postcss@<=8.5.22: '>=8.5.23'
    undici@<6.28.0: '^7.29.0'

patchedDependencies:
    discord.js: patches/discord.js.patch
