name: Create Release

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v6
            - name: Release
              uses: softprops/action-gh-release@v3
              with:
                  name: P.R.I.T. Bot ${{ github.ref_name }}
                  draft: true
